#!/usr/bin/env node
// scripts/build-prod.js – Production installer builder

import { execSync, execFileSync } from 'child_process';
import { existsSync, readdirSync, statSync, rmSync, renameSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { readFileSync } from 'fs';

const ROOT = process.cwd();
const RED = '\x1b[31m';
const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const CYAN = '\x1b[36m';
const RESET = '\x1b[0m';

// Optional CLI arg: config file to build with (defaults to the production
// config). Lets `npm run build:test` reuse this whole pipeline against
// electron-builder.test.json5 (distinct appId → installs side-by-side
// instead of overwriting the production app).
const CONFIG_FILE = process.argv[2] || 'electron-builder.json5';

/* MKCP_EMBED_ENV=1 — build a PROVISIONING installer that carries server/.env.
 *
 * Ordinary releases are credential-free, which is the only reason they can be
 * published to `kaxx4/MKCP-V4` at all: that repo is PUBLIC, and server/.env
 * holds the live Supabase service-role key, which bypasses RLS on every table.
 *
 * A provisioning installer exists for the one job the credential-free one
 * cannot do: credentialing a machine that has never had a .env. It writes the
 * key into `<userData>/.env` on first run (see loadPackagedEnv in
 * public/electron.js), after which that machine takes ordinary over-the-air
 * updates forever and never needs one of these again.
 *
 * Two guardrails, because getting this wrong publishes a live key:
 *   1. It builds into its OWN output directory, so the `latest.yml` and .exe
 *      that the release step uploads can never be the ones carrying the key.
 *   2. Publishing is refused outright, not warned about.
 */
const EMBED_ENV = process.env.MKCP_EMBED_ENV === '1';
const EMBED_OUTPUT_DIR = 'release-provisioning';
const EMBED_CONFIG_FILE = 'electron-builder.provisioning.json5';

function step(msg) { console.log(`\n${CYAN}▶ ${msg}${RESET}`); }
function ok(msg) { console.log(`${GREEN}✓${RESET} ${msg}`); }
function fail(msg) { console.error(`${RED}✗ ${msg}${RESET}`); }
function warn(msg) { console.warn(`${YELLOW}⚠${RESET} ${msg}`); }

function run(cmd, opts = {}) {
  console.log(`  $ ${cmd}`);
  try {
    execSync(cmd, { stdio: 'inherit', ...opts });
    return true;
  } catch {
    fail(`Command failed: ${cmd}`);
    if (opts.critical !== false) process.exit(1);
    return false;
  }
}

/** Read output dir from the active config using regex (avoids full JSON5 parse) */
function getOutputDir(configFile) {
  try {
    const raw = readFileSync(join(ROOT, configFile), 'utf8');
    // Extract: output: "someValue" — works with or without quoted keys
    const m = raw.match(/output\s*:\s*["']([^"']+)["']/);
    return m ? m[1] : 'release';
  } catch {
    return 'release';
  }
}

/* The two lines the provisioning config has to change, matched EXACTLY.
   A loose regex here is the dangerous kind of clever: if it silently failed to
   match, the build would look like it embedded the key and ship without it —
   or, far worse, match the wrong array and put the key somewhere the release
   step uploads. An exact string that must appear exactly once fails loudly
   the day someone reformats the config, which is the behaviour worth having. */
const EMBED_FILTER_FROM = `filter: ["dist/**/*", "package.json", "node_modules/**/*"],`;
const EMBED_FILTER_TO = `filter: ["dist/**/*", "package.json", "node_modules/**/*", ".env"],`;
const EMBED_OUTPUT_FROM = `output: "release2"`;

/**
 * Write a one-off electron-builder config that bundles server/.env and builds
 * into its own directory. Returns the config filename.
 */
function writeProvisioningConfig() {
  const raw = readFileSync(join(ROOT, CONFIG_FILE), 'utf8');

  for (const [label, needle] of [['extraResources filter', EMBED_FILTER_FROM], ['output dir', EMBED_OUTPUT_FROM]]) {
    const hits = raw.split(needle).length - 1;
    if (hits !== 1) {
      fail(`Cannot build a provisioning installer: expected exactly one ${label} line in ${CONFIG_FILE}, found ${hits}.`);
      fail(`Looked for: ${needle}`);
      fail('Refusing to guess — fix the marker in this script rather than loosening the match.');
      process.exit(1);
    }
  }

  const out = raw
    .replace(EMBED_FILTER_FROM, EMBED_FILTER_TO)
    .replace(EMBED_OUTPUT_FROM, `output: "${EMBED_OUTPUT_DIR}"`);

  const banner =
    '// GENERATED by scripts/build-prod.js for MKCP_EMBED_ENV=1. Do not commit; do not publish\n' +
    '// anything built with it. The installer it produces carries the live Supabase\n' +
    '// service-role key. Deleted automatically when the build finishes.\n';
  writeFileSync(join(ROOT, EMBED_CONFIG_FILE), banner + out);
  return EMBED_CONFIG_FILE;
}

/** Try to clear the output directory, with retries for locked files */
async function clearOutputDir(outDir) {
  if (!existsSync(outDir)) return; // Nothing to clear

  const asar = join(outDir, 'win-unpacked', 'resources', 'app.asar');
  if (!existsSync(asar)) {
    // No asar — try normal delete
    try { rmSync(outDir, { recursive: true, force: true }); } catch {}
    return;
  }

  // asar exists — Windows Defender may lock it briefly; retry with delays
  console.log(`  Clearing previous build (may take a moment if Defender scans it)...`);
  for (let attempt = 1; attempt <= 8; attempt++) {
    try {
      rmSync(asar, { force: true });
      rmSync(outDir, { recursive: true, force: true });
      console.log(`  ${GREEN}✓${RESET} Previous build cleared`);
      return;
    } catch (err) {
      if (attempt < 8) {
        process.stdout.write(`  Attempt ${attempt}/8 — file locked, retrying in 3s...\r`);
        await new Promise(r => setTimeout(r, 3000));
      } else {
        // Last resort: rename the old dir out of the way
        const backup = outDir + '_old';
        try {
          if (existsSync(backup)) rmSync(backup, { recursive: true, force: true });
          renameSync(outDir, backup);
          warn(`Could not delete locked build — moved to ${backup}_old`);
        } catch {
          fail(`Cannot clear ${outDir}: ${err.message}`);
          fail('Close any running MK Cycles Dashboard instances and retry.');
          process.exit(1);
        }
      }
    }
  }
}

async function main() {
  console.log(`\n${YELLOW}════════════════════════════════════════${RESET}`);
  console.log(`  MK Cycles Dashboard – Build (${CONFIG_FILE})`);
  console.log(`${YELLOW}════════════════════════════════════════${RESET}\n`);

  /* Refused, not warned about. `--publish always` on an embedded build would
     upload the service-role key to a public Releases page, and an upload is
     not a thing you get to take back — the file is fetched and mirrored within
     minutes of appearing. The two flags are mutually exclusive by construction
     so there is no ordering of them that produces that outcome. */
  if (EMBED_ENV && process.env.MKCP_PUBLISH === 'always') {
    fail('MKCP_EMBED_ENV=1 and MKCP_PUBLISH=always cannot be combined.');
    fail('An embedded build carries the live Supabase service-role key, and kaxx4/MKCP-V4 is a PUBLIC repository.');
    fail('Build it without MKCP_PUBLISH and carry the .exe to the machine; publish the credential-free build instead.');
    process.exit(1);
  }

  let activeConfig = CONFIG_FILE;
  if (EMBED_ENV) {
    const envPath = join(ROOT, 'server', '.env');
    if (!existsSync(envPath)) {
      fail(`MKCP_EMBED_ENV=1 but ${envPath} does not exist — there is nothing to embed.`);
      fail('Without it this build would be silently identical to an ordinary one, which is the worst of both outcomes.');
      process.exit(1);
    }
    /* Say which ROLE is going into the installer, and refuse the one that
       produces a working install that does nothing.

       `MKCP_TALLY_ROLE` decides whether the machine claims push-queue jobs. A
       provisioning installer exists to put a machine to work, so embedding
       `sandbox` credentials it to sit idle — and the symptom is a drain agent
       that refuses every job with nothing on screen saying why, which is the
       exact failure this whole provisioning path was built to end.

       It is easy to hit by accident: the build machine's own server/.env holds
       whatever role THAT machine needs, which for a sandbox is `sandbox`. The
       value is right for the builder and wrong for the target. */
    const role = (readFileSync(envPath, 'utf8').match(/^\s*MKCP_TALLY_ROLE\s*=\s*(\S+)/m) || [])[1] || '(unset)';
    warn('MKCP_EMBED_ENV=1 — this installer will CARRY server/.env (the live Supabase service-role key).');
    warn(`Output goes to ${EMBED_OUTPUT_DIR}/ and must never be uploaded. Treat the .exe as the secret it contains.`);
    warn(`Embedded MKCP_TALLY_ROLE=${role} — the machine you install this on will take that role.`);
    if (role !== 'primary' && process.env.MKCP_EMBED_ROLE_OK !== '1') {
      fail(`Refusing to build: MKCP_TALLY_ROLE=${role} in ${envPath}.`);
      fail('A machine provisioned with this will start, connect, and then refuse every push-queue job.');
      fail('Set it to `primary` in server/.env for the target machine, or pass MKCP_EMBED_ROLE_OK=1 if a second sandbox is genuinely what you want.');
      process.exit(1);
    }
    // Generated LAST, so a refusal above leaves nothing behind to be run later
    // from a shell that happens to have a GitHub token in it.
    activeConfig = writeProvisioningConfig();
  }

  const outputDir = getOutputDir(activeConfig);

  // Step 0: Clear previous build (handles locked app.asar)
  step('Clearing previous build output...');
  await clearOutputDir(join(ROOT, outputDir));

  // Step 1: Ensure server has ALL deps (including @types/* needed for tsc)
  step('Installing server dependencies (including dev for build)...');
  run('npm install', { cwd: join(ROOT, 'server') });
  ok('Server dependencies ready');

  /* Snapshot the manifest before electron-builder runs.
     `extraMetadata` makes electron-builder generate a TRANSFORMED package.json
     for the packaged app — name/version/main/dependencies, with `scripts` and
     `devDependencies` stripped. On 15-Sep-2026 a publish run wrote that
     transformed copy over the SOURCE file: 17 scripts and 22 devDependencies
     gone, `npm run build` answering "Missing script: build", and the damage
     committed before anyone noticed because the file still looked like valid
     JSON. Restored from git.
     Cheap insurance: remember it, and put it back if it comes out thinner. */
  const pkgPath = join(ROOT, 'package.json');
  const pkgBefore = readFileSync(pkgPath, 'utf8');

  // Step 2: Build React frontend
  step('Building React frontend...');
  run('npm run build');
  if (!existsSync(join(ROOT, 'dist/index.html'))) {
    fail('dist/index.html not created');
    process.exit(1);
  }
  ok('React frontend built → dist/');

  // Step 3: Build Express server (needs @types/* from step 1)
  step('Building Express server...');
  run('npm run build:server');
  if (!existsSync(join(ROOT, 'server/dist/index.js'))) {
    fail('server/dist/index.js not created');
    process.exit(1);
  }
  ok('Express server built → server/dist/');

  // Step 3.5: Strip server dev-dependencies before packaging.
  // typescript (~70 MB), tsx + esbuild (~20 MB), @types/node (~12 MB) are only
  // needed to compile the server — they have zero runtime use. Pruning them here
  // cuts ~100 MB from server/node_modules before electron-builder bundles it into
  // the asar, shrinking the installer and reducing RAM needed for module resolution.
  step('Pruning server dev-dependencies (typescript, tsx, @types)...');
  run('npm prune --omit=dev', { cwd: join(ROOT, 'server') });
  ok('Server devDeps pruned — installer will be ~100 MB smaller');

  // Step 4: Run electron-builder
  step(`Building Electron installer (${CONFIG_FILE})...`);
  /* Publishing is opt-in, and it happens INSIDE this build rather than as a
     second electron-builder run afterwards. That matters: the dev-dependency
     prune above is undone once this function returns, so a second build would
     package `server/node_modules` with typescript and friends in it — roughly
     100 MB of devDeps — and upload an artifact nobody had tested. One build,
     one artifact, optionally published. */
  const publish = process.env.MKCP_PUBLISH === 'always' ? 'always' : 'never';
  if (publish === 'always') warn('MKCP_PUBLISH=always — this build will be UPLOADED to GitHub Releases.');
  try {
    run(`npx electron-builder --win --config ${activeConfig} --publish ${publish}`);
  } finally {
    // The generated config names no secret, but leaving it behind invites
    // someone to run it deliberately later, from a shell with a GH token in it.
    if (EMBED_ENV) {
      try { rmSync(join(ROOT, EMBED_CONFIG_FILE), { force: true }); } catch {}
    }
  }

  // Step 4.5: Restore server devDependencies so the workspace stays usable for development.
  step('Restoring server dev-dependencies for development...');
  run('npm install', { cwd: join(ROOT, 'server') });
  ok('Server devDeps restored');

  /* Step 4.6: Did the build eat the manifest? See the snapshot above. */
  const pkgAfter = readFileSync(pkgPath, 'utf8');
  if (pkgAfter !== pkgBefore) {
    const before = JSON.parse(pkgBefore);
    const after = JSON.parse(pkgAfter);
    const lostScripts = Object.keys(before.scripts || {}).length - Object.keys(after.scripts || {}).length;
    const lostDev = Object.keys(before.devDependencies || {}).length - Object.keys(after.devDependencies || {}).length;
    if (lostScripts > 0 || lostDev > 0) {
      warn(`package.json was rewritten by the build — ${lostScripts} script(s) and ${lostDev} devDependency(ies) lost. Restoring it.`);
      writeFileSync(pkgPath, pkgBefore);
      ok('package.json restored');
    }
  }

  // Step 5: Verify output
  step('Verifying output...');
  const outDir = join(ROOT, outputDir);
  if (!existsSync(outDir)) {
    fail(`${outputDir}/ not created`);
    process.exit(1);
  }

  const files = readdirSync(outDir);
  const exe = files.find((f) => f.endsWith('.exe'));

  if (!exe) {
    fail(`No .exe file in ${outputDir}/`);
    process.exit(1);
  }

  const stats = statSync(join(outDir, exe));
  const sizeMB = (stats.size / 1024 / 1024).toFixed(1);
  ok(`Installer created: ${exe} (${sizeMB} MB)`);

  /* Whether the key is in there is not something to infer from a flag being
     set — an extraResources filter that quietly stopped matching would produce
     a perfectly successful build of exactly the wrong artifact, and the only
     symptom would be an office machine that still comes up with the push agent
     disabled. Look at the unpacked tree and say what is actually there. */
  const packedEnv = join(outDir, 'win-unpacked', 'resources', 'server', '.env');
  if (EMBED_ENV) {
    if (!existsSync(packedEnv)) {
      fail(`MKCP_EMBED_ENV=1 but the packaged app has no ${packedEnv}.`);
      fail('The installer would install without credentials. Not shipping it.');
      process.exit(1);
    }
    ok(`Verified: server/.env is inside the package (${statSync(packedEnv).size} bytes)`);
  } else if (existsSync(packedEnv)) {
    fail(`This build is meant to be credential-free, but ${packedEnv} exists.`);
    fail('kaxx4/MKCP-V4 is PUBLIC — publishing this artifact would expose the Supabase service-role key.');
    process.exit(1);
  } else {
    ok('Verified: no .env inside the package');
  }

  /* The .env check above guards ONE way a secret gets into the artifact, and on
     19-Sep-2026 a second one was found the hard way.

     `public/sample/transactions.json` and `public/sample/masters.json` held real
     business data — 13 GST e-invoice QR payloads (signed by NIC, carrying seller
     and buyer GSTINs, consignee names, pincodes, invoice numbers, IRNs and
     totals) and 7 more GSTINs with 23 party names. Both were in `.gitignore`,
     so somebody had already judged them too sensitive for the repo. But
     .gitignore only keeps a file out of the REPO: Vite copies `public/` into
     `dist/`, and extraResources bundles `dist/**` into the installer. They
     shipped in every build, and the next `--publish always` would have put
     customers' GSTINs and addresses on a PUBLIC GitHub release.

     So: read the packed asar and refuse anything that looks like a real
     identity document. Two signatures, both cheap and both specific enough not
     to fire on code — a GSTIN is a fixed 15-character shape, and an RS256 JWT
     with `iss` NIC is a government e-invoice signature. Nothing legitimate in
     this app's source contains either. */
  const asarPath = join(outDir, 'win-unpacked', 'resources', 'app.asar');
  if (existsSync(asarPath)) {
    const blob = readFileSync(asarPath).toString('latin1');
    const gstins = new Set(blob.match(/[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]Z[0-9A-Z]/g) || []);
    /* `eyJhbGciOiJSUzI1NiJ9` is the base64 of {"alg":"RS256"} EXACTLY, and the
       real payloads carry {"alg":"RS256","typ":"JWT"} — a different string. The
       strict form read 0 on a file holding 13 of them while the GSTIN signal
       caught it, i.e. half the guard was dead and looked fine. Match any RS*
       header instead, and verify against sample-data/ when changing this. */
    const nicJwts = (blob.match(/eyJhbGciOiJS[A-Za-z0-9_-]{6,}\.eyJ[A-Za-z0-9_-]{40,}/g) || []).length;
    if (gstins.size || nicJwts) {
      fail(`The packaged app contains real business data: ${gstins.size} GSTIN(s), ${nicJwts} e-invoice signature(s).`);
      fail('kaxx4/MKCP-V4 is PUBLIC — publishing this would expose customer identities.');
      fail('Look for sample/fixture data under public/, which Vite copies into dist/.');
      process.exit(1);
    }
    ok('Verified: no GSTINs or e-invoice signatures in the package — safe to publish');

    /* The renderer's READ credentials, verified present rather than assumed.
     *
     * Found 22-Sep-2026 from the app's own Supabase Cloud panel: "no read
     * client — this build has no Supabase read credentials", so the history and
     * push-log lists were permanently empty. The cause was that the repo root
     * had NO `.env` at all. Vite reads the root file, beside vite.config.ts;
     * `server/.env` is a different file for a different process, and having one
     * looks exactly like having the other until you check.
     *
     * Nothing failed. `import.meta.env.VITE_SUPABASE_URL` was simply undefined,
     * the renderer skipped building a client, and the build shipped — this
     * project's signature failure shape, and the reason the check belongs in the
     * build rather than in a panel that reports it after the fact.
     *
     * It reads the PACKED asar, not the environment, because what matters is
     * what got INLINED — a variable present at build time and then misspelled
     * or tree-shaken would still pass an env check. Counts and yes/no only; no
     * value is printed, though both are publishable and RLS-gated by design. */
    const hasUrl = /https:\/\/[a-z0-9]{20}\.supabase\.co/.test(blob);
    const hasPublishable = /sb_publishable_[A-Za-z0-9_-]{10,}/.test(blob)
      || /eyJ[A-Za-z0-9_-]+\.eyJ[A-Za-z0-9_-]*(cm9sZSI6ImFub24|InJvbGUiOiJhbm9u)/.test(blob);
    if (!hasUrl || !hasPublishable) {
      fail('The renderer has NO Supabase read credentials baked in.');
      fail(`  project URL inlined: ${hasUrl ? 'yes' : 'NO'} · publishable key inlined: ${hasPublishable ? 'yes' : 'NO'}`);
      fail('Vite reads the REPO ROOT .env (beside vite.config.ts), not server/.env.');
      fail('Copy .env.example to .env, fill both VITE_ values, and rebuild.');
      fail('Pushing would still work — only the history and push-log lists read');
      fail('empty, which looks identical to "nothing has synced".');
      process.exit(1);
    }
    ok('Verified: renderer carries its Supabase read credentials (URL + publishable key)');
  }

  console.log(`\n${GREEN}════════════════════════════════════════${RESET}`);
  console.log(`  ✅ BUILD COMPLETE`);
  console.log(`  📦 ${outputDir}/${exe}`);
  console.log(`  📏 ${sizeMB} MB`);
  console.log(`${GREEN}════════════════════════════════════════${RESET}\n`);

  if (EMBED_ENV) {
    console.log(`${YELLOW}  ⚠  This installer CARRIES the Supabase service-role key.${RESET}`);
    console.log(`     Carry it to the machine (USB), do not upload it, and delete it afterwards.`);
    console.log(`     On first run it writes the key to %APPDATA%\\mkcycles-dashboard-electron\\.env,`);
    console.log(`     after which that machine takes ordinary over-the-air updates and never`);
    console.log(`     needs a provisioning build again.\n`);
  }
}

main().catch((err) => {
  fail(`Build failed: ${err.message}`);
  process.exit(1);
});
